http:
    routers:
        allbackendrouter:
            rule: "Host(`telmanmac`) && Path(`/`)"
            service: allbackend
        app1router:
            rule: "Host(`telmanmac`) && Path(`/app1`)"
            service: app1backend
        app2router:
            rule: "Host(`telmanmac`) && Path(`/app2`)"
            service: app2backend
    services:
        app1backend:
            loadBalancer:
                servers:
                    - url: "http://telmanmac:1111/"
                    - url: "http://telmanmac:2222/"
        app2backend:
            loadBalancer:
                servers:
                    - url: "http://telmanmac:3333/"
                    - url: "http://telmanmac:4444/"
        allbackend:
            loadBalancer:
                servers:
                    - url: "http://telmanmac:1111/"
                    - url: "http://telmanmac:2222/"
                    - url: "http://telmanmac:3333/"
                    - url: "http://telmanmac:4444/"